### ISSUE TITLE
Occasional Empty search results

### ISSUE THREAD

**Issue by HansVraga** [USGS-WiM/merlin_django#88] opened 2017-03-13 20:28 UTC
Feedback from Mercury Lab
>Occasionally some searches come back empty, but when rerun come back with expected results

**Comment by aaronstephenson** [comment] 2017-03-22 03:04
I told John to let me know the next time he saw this, since I can then check the logs immediately. Otherwise this will be very difficult to reproduce.

**Comment by aaronstephenson** [comment] 2019-08-20 20:09
This may have been fixed in one of the many updates over the years; in any case, I have not heard them mention this is a very long time, closing.

**Closed by aaronstephenson** 2019-08-20 20:09 UTC
Labels: bug
